package servent.message;

public enum MessageType {
    WELCOME, START_DRAWING, STOP_DRAWING, REQUEST_RESULT, SEND_RESULT, PING, PONG, SUSPICIOUS_PORT, SUSPICIOUS_PING, SUSPICIOUS_PORT_CHECKED, SUSPICIOUS_PONG, NODE_BROKEN, NEW_SETUP, BACKUP, NEW_NODE
}
